
=head1 NAME

remote-viewer - a simple remote desktop client

=head1 SYNOPSIS

B<remote-viewer> [OPTIONS] URI

=head1 DESCRIPTION

B<remote-viewer> is a simple remote display client. The supported
protocols are SPICE and VNC.

=head1 OPTIONS

The following options are accepted when running C<remote-viewer>:

=over 4

=item -h, --help

Display command line help summary

=item -V, --version

Display program version number

=item -v, --verbose

Display information about the connection

=item -z PCT, --zoom=PCT

Zoom level of the display window in percentage. Range 10-200.

=item -f, --full-screen

Start with the window maximised to fullscreen

=item --spice-controller

Use the SPICE controller to initialize the connection with the SPICE
server. This option is used by the SPICE browser addons to allow web
page to start a client.

=item --debug

Print debugging information

=back

=head1 EXAMPLES

To connect to SPICE server on host "makai" with port 5900

   remote-viewer spice://makai:5900

To connect to VNC server on host "tsingy" with port 5900

   remote-viewer vnc://tsingy:5900

=head1 BUGS

Report bugs to the mailing list C<http://www.redhat.com/mailman/listinfo/virt-tools-list>

=head1 COPYRIGHT

Copyright (C) 2012 Red Hat, Inc., and various contributors.
This is free software. You may redistribute copies of it under the terms of the GNU General
Public License C<http://www.gnu.org/licenses/gpl.html>. There is NO WARRANTY, to the extent
permitted by law.

=head1 SEE ALSO

C<virt-viewer(1)>, the project website C<http://virt-manager.org>

=cut
